export const FETCH_LIST_LOCATION_REQUEST  = "@fetchListLocationReducer/FETCH_LIST_LOCATION_REQUEST";
export const FETCH_LIST_LOCATION_SUCCESS = "@fetchListLocationReducer/FETCH_LIST_LOCATION_SUCCESS";
export const FETCH_LIST_LOCATION_FAILED = "@fetchListLocationReducer/FETCH_LIST_LOCATION_FAILED";