export const FETCH_LIST_ROOMS_FOR_RENT_BY_ID_REQUEST  = "@fetchListRoomsForRentByIDReducer/FETCH_LIST_ROOMS_FOR_RENT_BY_ID_REQUEST";
export const FETCH_LIST_ROOMS_FOR_RENT_BY_ID_SUCCESS = "@fetchListRoomsForRentByIDReducer/FETCH_LIST_ROOMS_FOR_RENT_BY_ID_SUCCESS";
export const FETCH_LIST_ROOMS_FOR_RENT_BY_ID_FAILED = "@fetchListRoomsForRentByIDReducer/FETCH_LIST_ROOMS_FOR_RENT_BY_ID_FAILED";


export const DELETE_ROOM_REQUEST  = "@fetchListRoomsForRentByIDReducer/DELETE_ROOM_REQUEST";
export const DELETE_ROOM_SUCCESS = "@fetchListRoomsForRentByIDReducer/DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_FAILED = "@fetchListRoomsForRentByIDReducer/DELETE_ROOM_FAILED";