export const FETCH_DETAIL_LOCATION_REQUEST  = "@fetchDetailLocationReducer/FETCH_DETAIL_LOCATION_REQUEST";
export const FETCH_DETAIL_LOCATION_SUCCESS = "@fetchDetailLocationReducer/FETCH_DETAIL_LOCATION_SUCCESS";
export const FETCH_DETAIL_LOCATION_FAILED = "@fetchDetailLocationReducer/FETCH_DETAIL_LOCATION_FAILED";