export const EDIT_EVALUATE_REQUEST  = "@eidtEvaluateReducer/EDIT_EVALUATE_REQUEST";
export const EDIT_EVALUATE_SUCCESS = "@eidtEvaluateReducer/EDIT_EVALUATE_SUCCESS";
export const EDIT_EVALUATE_FAILED = "@eidtEvaluateReducer/EDIT_EVALUATE_FAILED";

export const FETCH_DETAIL_EVALUATE_REQUEST  = "@eidtEvaluateReducer/FETCH_DETAIL_EVALUATE_REQUEST";
export const FETCH_DETAIL_EVALUATE_SUCCESS = "@eidtEvaluateReducer/FETCH_DETAIL_EVALUATE_SUCCESS";
export const FETCH_DETAIL_EVALUATE_FAILED = "@eidtEvaluateReducer/FETCH_DETAIL_EVALUATE_FAILED";