export const UPLOAD_IMAGE_ROOM_REQUEST  = "@uploadImageReducer/UPLOAD_IMAGE_ROOM_REQUEST";
export const UPLOAD_IMAGE_ROOM_SUCCESS = "@uploadImageReducer/UPLOAD_IMAGE_ROOM_SUCCESS";
export const UPLOAD_IMAGE_ROOM_FAILED = "@uploadImageReducer/UPLOAD_IMAGE_ROOM_FAILED";

export const UPLOAD_IMAGE_LOCATION_REQUEST  = "@uploadImageReducer/UPLOAD_IMAGE_LOCATION_REQUEST";
export const UPLOAD_IMAGE_LOCATION_SUCCESS = "@uploadImageReducer/UPLOAD_IMAGE_LOCATION_SUCCESS";
export const UPLOAD_IMAGE_LOCATION_FAILED = "@uploadImageReducer/UPLOAD_IMAGE_LOCATION_FAILED";

